datalogics/datalogics.github.io

- Release_Notes.html
- index.html
Fix duplicated content.
Add link to release notes to top-level index.
> Fix duplicated content and add link to release notes to top-level index.

- Release_Notes.html
Update release notes for P2a release.
> Update release notes for P2a release.

- CPlusPlus/Acknowledgements.html
- CPlusPlus/Getting_Started.html
- CPlusPlus/index.html
- PDFConverter/Acknowledgements.html
- PDFConverter/Datalogics_specifics.html
- PDFConverter/Release_Notes.html
- PDFConverter/index.html
Add style and analytics to C++ index page, software acknowledgments and Getting started.
Add a back link from C/C++ docs to the top level.
Add PDF Converter files in a subdirectory
> Add style and analytics to C++ index page, software acknowledgments

- index.html
Create a top-level index page for all the products.
> Create a top-level index page for all the products.

- PDFConverter/Datalogics_specifics.html
Adds a list of changes made by Datalogics to PDFConverter
> NOR-417 -- Add Datalogics change list

- apdfl18/Release_Notes.html
moved SF#45777 and SF#45826 into New Features section
changed date to July 31, 2023
> 18.0.4 p2b 3

- FLIP2PDF/Acknowledgements.html
- FLIP2PDF/Release_Notes.html
- FLIP2PDF/index.html
- PDFOptimizer/Release_Notes.html
Also fix capitalization of FLIP2PDF.
> Update release notes for Optimizer.

- PDFOptimizer/Release_Notes.html
Update release notes for PDF Optimizer 3.3.0
> Update release notes for PDF Optimizer 3.3.0

- PDF2IMG/Release_Notes.html
Update Release Notes for v4.6.0
> PDF2IMG - Update Release Notes for v4.6.0

- apdfl18/CPlusPlus/APDFL18.0.4PlusP1z/resources/js/coverJS.js
- apdfl18/CPlusPlus/APDFL18.0.4PlusP2a/resources/js/coverJS.js
- Fix an issue where the cover pages search box would clear out the search entry after hitting the enter button
> Search box fix

- PDFConverter/Datalogics_specifics.html
Update the platform table & title to list all of the available platforms for the Datalogics PDF Converter SDK.
> Update platform table in PDF Converter Documentation

- apdfl18/Release_Notes.html
Be more specific about the new packages created.
> 18.0.4+P2c Release Notes update

- apdfl18/DotNet/ver.html
- apdfl18/DotNetFramework/ver.html
- apdfl18/Java/ver.html
- Replace previous version selection footer with an iframe containing ver.html
[APDFL-5336]: https://datalogics-jira.atlassian.net/browse/APDFL-5336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APDFL-5336 Add version selection to docs

- apdfl18/DotNet/ver.html
- apdfl18/DotNetFramework/ver.html
- apdfl18/Java/ver.html
[APDFL-5336]: https://datalogics-jira.atlassian.net/browse/APDFL-5336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> APDFL-5336 Add recognition for current version

- PDFConverter/Release_Notes.html
Release_notes.html for v3.2P1c.
To be reviewed by someone from SUPP
> Converter3.2P1c Updates to the Release_Notes.html

- apdfl18/Release_Notes.html
v18.0.4P2f Release_Notes.html update
> v18.0.4P2f Release_Notes.html

- PDFChecker/Release_Notes.html
- PDFOptimizer/Release_Notes.html
PDF Optimizer v3.4.1 Release_Notes.html
> Pdf optimizer3.4.1

- PDF2IMG/Release_Notes.html
Update the ReleaseNote.html for PDF2IMG4.7.0
> Update the ReleaseNote.html for PDF2IMG4.7.0

- PDF2IMG/Release_Notes.html
Updated a typo correction on the Release Note PDF2IMG4.7.0
> Updated a typo correction on the Release Note  PDF2IMG4.7.0

- apdfl18/Release_Notes.html
Please check my updates to the v18.0.4P2k release notest
> update to 18.0.4P2k Release_Notes.html

- apdfl18/Release_Notes.html
> typo edit to v18.0.4P2k Release_Notes.html

- apdfl18/Release_Notes.html
update to v18.0.4P2m release notes HTML
> update to v18.0.4P2m Release_Notes.html

- PDF2IMG/Release_Notes.html
Updated the Release Note for PDF2IMG4.8.0
> Updated the Release Note for PDF2IMG4.8.0

- apdfl18/CPlusPlus/Getting_Started.html
Remove address and update copyright.
> Remove address and update copyright.

- FLIP2PDF/Release_Notes.html
Please review and merge (if approved) the updates to FLIP2PDF v2.0.1 Release Notes.html
> updates to FLIP2PDF v2.0.1 Release_Notes.html

- apdfl15/Release_Notes.html
Please review and merge (if approved)
> Update to ADPFL v15.0.4P8p Release_Notes.html

- apdfl18/DotNet/ver.html
- apdfl18/DotNetFramework/ver.html
- apdfl18/Java/ver.html
> Fix P2p version.

- apdfl18/Release_Notes.html
SUPP team. Please review and if approved merge the updates to v18.0.4P2r release notes
> Update to v18.0.4P2r Release_Notes.html

- FormsExtension/Release_Notes.html
SUPP. please review and if approved merge
> Update to FormsExtension v2.3.0 Release_Notes.html

- FormsFlattener/Release_Notes.html
SUPP please review and if approved, merge
> Update to FormsFlattener v3.1.0 Release_Notes.html

- apdfl18/Release_Notes.html
SUPP please review updates to v18.0.4P2u release notes.html
If approved, please merge
> Updates to ADPFL v18.0.4P2u Release_Notes.html

- PDFConverter/Release_Notes.html
Updates to Converter v3.2P1g release notes.html
SUPP please review and if approved, merge
> Updates to Converter v3.2P1g Release_Notes.html

- apdfl18/Release_Notes.html
SUPP please review and if approved please merge the PR
> Updates to APDFL 18.0.4P2w Release_Notes.html

- FormsExtension/index.html
Fix title and put it at top.
Remove 'except for QR codes'
Add a Back link to the index.html
> Fix FE title

- FormsExtension/index.html
> merge develop to main

- apdfl18/Release_Notes.html
SUPP please review. 
Note that if this is approved, this is going to be merged to Develop branch first and a new PR to merge to main has to be created.
> update to v18.0.4P2x Release_Notes.html

- apdfl18/Release_Notes.html
Updates to v18.0.4P2z release notes. Review and merge to Develop branch
> Update to v18.0.4P2z Release_Notes.html

- PDFOptimizer/Release_Notes.html
> Release notes for the latest version (v3.5.0).

- apdfl18/CPlusPlus/API_Reference.html
Point API_Reference href to index.html, otherwise it opens the directory.
> Point API_Reference href to index.html

- FormsFlattener/Release_Notes.html
Documents the release date and new features of PDFFormsFlattener v4.0.0
> Update FF 4.0 Release_Notes

- apdfl15/Release_Notes.html
Reverts datalogics/datalogics.github.io#154
All PRs have to go to `develop` first
> Revert "Update Release_Notes.html"

- FormsFlattener/Release_Notes.html
PDF Forms Flattener v4.1.0 Release notes update.
> PDF Forms Flattener v4.1.0 Release notes update.

- FormsFlattener/Release_Notes.html
- PDFOptimizer/Release_Notes.html
> Merge FF v4.1.0 Release notes

- apdfl18/Release_Notes.html
Took Joffre's Release Notes, removed Brotli line item, fixed grammar in one sentence.
> Update Release_Notes for 18.0.5+P1b.html

- apdfl18/Release_Notes.html
update to the release notes for 18.0.5P1c
> Update 18.0.5P1c Release_Notes.html

- apdfl18/Release_Notes.html
updated release notes for v18.0.4P1d
> Update Release_Notes.html for v18.0.4P1d

- apdfl18/DotNet/API_Reference.html
- apdfl18/DotNetFramework/API_Reference.html
- apdfl18/Java/API_Reference.html
> Add explicit links to the API reference docs for each interface.

- apdfl18/DotNet/API_Reference.html
- apdfl18/DotNetFramework/API_Reference.html
- apdfl18/Java/API_Reference.html
Merge develop to main to get new API Reference links for all APDFL interfaces.
> Develop to main

- PDFConverter/Release_Notes.html
release notes updated for v3.2P1m
> Update Release_Notes.html v3.2P1m

- index.html
> redirect to the new site.
